### ISSUE TITLE
lambda 2.4 dependency cannot be resolved when building locally with mvn clean package

### ISSUE THREAD

**Issue by theseagull** [satyagraha/gfm_viewer#88]
unfortunately the .\ext-deps\pom.xml has a dependency to google code lambdaj which seems to not exist anymore at the provided repository address https://lambdaj.googlecode.com/svn/trunk

Can anybody please provide a buildable version? 
Thank you so much
KR Mario

**Comment by paulvi** [comment]
2.4 was used, says https://github.com/satyagraha/gfm_viewer/blob/master/ext-deps/pom.xml#L80

2.3.3 should be available for download as it is on maven Central
https://javalibs.com/artifact/com.googlecode.lambdaj/lambdaj  
so try to play with different versions, then maybe external repository is not needed at all.

Otherwise it is possible to get old released binaries and extract from there.
But if the lambdaj project is dead, in long run it is better re-write to some other lib and to get read of lambdaj.

Anyway, wait if the author @satyagraha can express his view.

**Comment by satyagraha** [comment]
The **lambdaj** project has been migrated to GitHub: https://github.com/mariofusco/lambdaj. What you can do is:
- fork it to your own area
- clone the fork onto your own computer
- checkout the 2.4 commit: 5d1180402e19c4f763604ea668085f2d099b4d52
- do `mvn install` to put that release into your local artifacts repo
